### ISSUE TITLE
Isomorphic-fetch front end request not working

### ISSUE THREAD

**Issue by adcpm** [adcpm/steemconnect#6]
On Busy website, isomorphic-fetch respond with isAuthenticated = false while https://steemconnect.com/api/verify show me isAuthenticated = true 

Via Busy:
![image](https://cloud.githubusercontent.com/assets/16245250/19299451/90674b7a-907e-11e6-8660-b4874237109f.png)

On this url https://steemconnect.com/api/verify
![image](https://cloud.githubusercontent.com/assets/16245250/19299469/ab6391ae-907e-11e6-83a6-ea8b5a5c4787.png)

Using raw ajax request i got the same issue before till i used this:
xmlHttp.withCredentials = true;

I'm not sure what is the cause because withCredentials seem to be setup with isomorphic-fetch. Could be a problem of settings? Any ideas?

**Comment by yamadapc** [comment]
I think `withCredentials` is on another codebase using `superagent`, it wasn't here
